/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import processing.core.PApplet;

public class Balls extends PApplet {

    private final int screenHeight = 480;
    private final int screenWidth = 640;
    private final int ball1_speed = 1, ball2_speed =2, ball3_speed = 3, ball4_speed = 4;
    int ballDiameter = 20;
    int ball1_x = 0, ball1_y = 0;
    int ball2_x = 0, ball2_y = 0;
    int ball3_x = 0, ball3_y = 0;
    int ball4_x = 0, ball4_y = 0;

    @Override
    public void settings() {
        super.settings();
        size(screenWidth, screenHeight);
    }

    @Override
    public void setup() {
        super.setup();
        ball1_y = (int) (screenHeight * ((double)1/(double)5));
        ball2_y = (int) (screenHeight * ((double)2/(double)5));
        ball3_y = (int) (screenHeight * ((double)3/(double)5));
        ball4_y = (int) (screenHeight * ((double)4/(double)5));
    }

    public void drawBalls(){
        System.out.println("Setup");
        ellipse(ball1_x, ball1_y, ballDiameter, ballDiameter);
        ellipse(ball2_x, ball2_y, ballDiameter, ballDiameter);
        ellipse(ball3_x, ball3_y, ballDiameter, ballDiameter);
        ellipse(ball4_x, ball4_y, ballDiameter, ballDiameter);
        println(ball1_y, ball2_y, ball3_y);
    }

    @Override
    public void draw() {
        ball1_x += ball1_speed;
        ball2_x += ball2_speed;
        ball3_x += ball3_speed;
        ball4_x += ball4_speed;
        drawBalls();
    }

    public static void main(String[] args) {
        PApplet.main("Balls", args);
    }
}
