package org.tw;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import processing.core.PApplet;

public class Balls extends PApplet {

    private final int screenHeight = 480;
    private final int screenWidth = 640;
    private final int ballDiameter = 20, numberOfBalls = 4;
    int[] ballsXPositions = new int[numberOfBalls], ballsYPositions = new int[numberOfBalls], ballSpeeds = new int[numberOfBalls];

    @Override
    public void settings() {
        super.settings();
        size(screenWidth, screenHeight);
    }

    @Override
    public void setup() {
        super.setup();
        for(int ballCounter=0; ballCounter < numberOfBalls; ballCounter++){
            ballsXPositions[ballCounter] = 0;
            ballsYPositions[ballCounter] = getBallsYPosition(ballCounter);
            ballSpeeds[ballCounter] = ballCounter+1;
        }
    }

    private int getBallsYPosition(int ballSerialNumber){
        return (int) (screenHeight * ((double)(ballSerialNumber+1)/(double)(numberOfBalls+1)));
    }

    @Override
    public void draw() {
        for(int ballCounter=0; ballCounter < numberOfBalls; ballCounter++){
            ballsXPositions[ballCounter] += ballSpeeds[ballCounter];
            ellipse(ballsXPositions[ballCounter], ballsYPositions[ballCounter], ballDiameter, ballDiameter);
        }
    }

    public static void main(String[] args) {
        PApplet.main("org.tw.Balls", args);
    }
}
